template = "https://github.com/giellalt/template-lang-und"
rev_id = 285
template_sha = "dc60d9e35b17842271a5a82c114510f9ff1a3d72"

[replacements]
__GLOTTOLOG_ID__ = "ikpe1245"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-txi"
__UND2C__ = "txi"
__UNDEFINED__ = "Ikpeng"
__UND__ = "txi"
